service: async-operations
frameworkVersion: "3"

custom:
  memsize:
    prod: 1024 # lower cost & higher performance https://docs.aws.amazon.com/lambda/latest/operatorguide/computing-power.html
    dev: 512
  timeout:
    prod: 10
    dev: 6

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'} #dev by default
  httpApi:
    disableDefaultEndpoint: true

constructs:
  collect-action-run-worker:
    type: queue
    worker:
      handler: lib/serverless-index.CollectActionRun.worker
      memorySize: ${self:custom.memsize.${self:provider.stage}, 1024}
      timeout: ${self:custom.timeout.${self:provider.stage}, 10}
      runtime: nodejs16.x
      fifo: true
      environment:
        PG_URI: ${env:PG_URI}

functions:
  collect-action-run-receiver:
    handler: lib/serverless-index.CollectActionRun.receiver
    description: Receiver to collect ActionRun statistics from HTTP endpoint. Passes it to another Queue.
    events:
      - httpApi:
          method: post
          path: /collect
          cors: true
          async: true
    environment:
      QUEUE_URL: ${construct:collect-action-run-worker.queueUrl}
    memorySize: ${self:custom.memsize.${self:provider.stage}, 1024}
    timeout: ${self:custom.timeout.${self:provider.stage}, 10}
    runtime: nodejs16.x

plugins:
  - serverless-lift
