name: Deploy Prod Client
on:
  push:
    paths:
      - src/**
      - ./*
    branches:
      - staging
  workflow_dispatch:

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: test functions
        run: | 
          npm install
          npm run test
  
  deploy-client:
    runs-on: ubuntu-latest
    needs: test-client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Deploy Client
        run: |
          npm install -g firebase-tools
           
          # Install dependencies
          npm install

          # Build project
          npm run build

          firebase deploy --project gh-action-stats --only hosting --token $FIREBASE_TOKEN
        env:
          ROLLUP_WATCH: false
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
 
