name: BackEnd tests
on:
  push:
    paths:
      - functions/**
  workflow_dispatch:

jobs:
  # test-client:
  #   runs-on: ubuntu-latest

  #   defaults:
  #     run:
  #       working-directory: ./
    
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '16'
  #     - name: Install dependencies
  #       run: |
  #         npm install
  #     - name: Test Client
  #       run: |
  #         npm run test

  test-functions:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./functions
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm install
        
      - name: Test Functions
        run: |
          npm run test
        env: 
          PG_URI: postgresql://postgres:postgres@localhost:5432/postgres


