name: Test Application
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: test server
        working-directory: ./functions
        run: | 
          npm install
          npm run test


  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: test client
        run: |
          npm install
          npm run test

        
